version: "3.8"
   
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  backend:
    container_name: backend
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    depends_on:
      - redis

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - redis



volumes:
  static_volume:
  media_volume:
